# Generated by Django 2.0 on 2018-02-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_types',
            field=models.CharField(choices=[('seeker', 'Jobseeker'), ('recruiters', 'Recruiters')], default='seeker', max_length=10),
        ),
    ]
