# Generated by Django 2.0 on 2018-01-20 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post_name', models.CharField(max_length=100)),
                ('Stream', models.CharField(max_length=100)),
                ('Percent_Criteria', models.IntegerField()),
                ('Salary', models.IntegerField()),
                ('Experience', models.IntegerField()),
                ('Vacancy', models.IntegerField()),
                ('Deadline', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='recruitersdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(max_length=100)),
                ('Mobile_Number', models.IntegerField()),
                ('City', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('recruiter_id', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='seekersdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Birth_date', models.DateField()),
                ('Gender', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('Mobile_Number', models.IntegerField()),
                ('secondary_board', models.CharField(max_length=100)),
                ('secondary_percent', models.IntegerField()),
                ('senior_board', models.CharField(max_length=100)),
                ('senior_percent', models.IntegerField()),
                ('College_name', models.CharField(max_length=100)),
                ('Stream', models.CharField(max_length=100)),
                ('Graduation_percent', models.IntegerField()),
                ('seeker_id', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
