# Generated by Django 2.0 on 2018-01-23 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20180122_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seekersdetail',
            old_name='seeker_id',
            new_name='Id',
        ),
    ]
