# Generated by Django 2.0 on 2018-01-24 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0004_auto_20180123_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='seekersdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Birth_date', models.DateField()),
                ('Gender', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Mobile_Number', models.IntegerField()),
                ('secondary_board', models.CharField(max_length=100)),
                ('secondary_percent', models.IntegerField()),
                ('senior_board', models.CharField(max_length=100)),
                ('senior_percent', models.IntegerField()),
                ('College_name', models.CharField(max_length=100)),
                ('Stream', models.CharField(max_length=100)),
                ('Graduation_percent', models.IntegerField()),
                ('Id', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='seekersdetail',
            name='Id',
        ),
        migrations.DeleteModel(
            name='seekersdetail',
        ),
    ]
