# Generated by Django 2.0 on 2018-01-24 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20180124_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seekersdetails',
            name='Gender',
        ),
    ]
