# Generated by Django 2.0 on 2018-02-09 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0007_posts_recruiter_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users_Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Companyid', models.CharField(max_length=100)),
                ('Apply', models.IntegerField(default=2)),
                ('Postid', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='register.posts')),
                ('Seekerid', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
