# Generated by Django 2.0 on 2018-02-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_users_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_apply',
            name='Apply',
            field=models.IntegerField(default=0),
        ),
    ]
