# Generated by Django 2.0 on 2018-02-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_auto_20180209_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitersdetail',
            name='About',
            field=models.CharField(default='abc', max_length=1000),
        ),
    ]
