# Generated by Django 2.0 on 2018-02-09 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_auto_20180209_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_apply',
            name='Companyid',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
