# Generated by Django 2.0 on 2018-02-09 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0014_auto_20180209_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_apply',
            name='Companyid',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='register.recruitersdetail'),
        ),
    ]
