# Generated by Django 2.0 on 2018-02-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0015_auto_20180209_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitersdetail',
            name='company_logo',
            field=models.FileField(default=0, upload_to=''),
        ),
    ]
