# Generated by Django 2.0 on 2018-06-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0017_auto_20180211_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='educational',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondary_school', models.CharField(max_length=100)),
                ('secondary_percent', models.FloatField()),
                ('senior_school', models.CharField(max_length=100)),
                ('senior_percent', models.FloatField()),
                ('College_name', models.CharField(max_length=100)),
                ('Stream', models.CharField(max_length=100)),
                ('Graduation_percent', models.IntegerField()),
                ('Skills', models.CharField(max_length=50)),
                ('exp_1', models.CharField(max_length=50)),
                ('exp_1_about', models.CharField(max_length=50)),
                ('exp_2', models.CharField(max_length=50)),
                ('exp_2_about', models.CharField(max_length=50)),
                ('Resume', models.FileField(default=0, upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='seekersdetails',
            old_name='College_name',
            new_name='State',
        ),
        migrations.RenameField(
            model_name='seekersdetails',
            old_name='Stream',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='seekersdetails',
            name='Graduation_percent',
        ),
        migrations.RemoveField(
            model_name='seekersdetails',
            name='Resume',
        ),
        migrations.RemoveField(
            model_name='seekersdetails',
            name='secondary_board',
        ),
        migrations.RemoveField(
            model_name='seekersdetails',
            name='secondary_percent',
        ),
        migrations.RemoveField(
            model_name='seekersdetails',
            name='senior_board',
        ),
        migrations.RemoveField(
            model_name='seekersdetails',
            name='senior_percent',
        ),
    ]
