# Generated by Django 2.0 on 2018-06-16 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0018_auto_20180616_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='educational',
            name='Id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='educational',
            name='exp_1_about',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='educational',
            name='exp_2_about',
            field=models.CharField(max_length=100),
        ),
    ]
