# Generated by Django 2.0 on 2018-06-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0020_auto_20180616_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekersdetails',
            name='College_name',
            field=models.CharField(default='M.B.M Engineering College', max_length=100),
        ),
        migrations.AddField(
            model_name='seekersdetails',
            name='Graduation_percent',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='seekersdetails',
            name='Resume',
            field=models.FileField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='seekersdetails',
            name='Skills',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='seekersdetails',
            name='Stream',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='seekersdetails',
            name='exp_1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='seekersdetails',
            name='exp_1_about',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='seekersdetails',
            name='exp_2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='seekersdetails',
            name='exp_2_about',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='seekersdetails',
            name='secondary_percent',
            field=models.FloatField(default=70),
        ),
        migrations.AddField(
            model_name='seekersdetails',
            name='secondary_school',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='seekersdetails',
            name='senior_percent',
            field=models.FloatField(default=70),
        ),
        migrations.AddField(
            model_name='seekersdetails',
            name='senior_school',
            field=models.CharField(default='', max_length=100),
        ),
    ]
