# Generated by Django 2.0 on 2018-06-16 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0021_auto_20180616_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seekersdetails',
            name='exp_2',
        ),
        migrations.RemoveField(
            model_name='seekersdetails',
            name='exp_2_about',
        ),
    ]
